// Code generated by protoc-gen-go. DO NOT EDIT.
// source: router.proto

package router

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RouterInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouterInfo) Reset()         { *m = RouterInfo{} }
func (m *RouterInfo) String() string { return proto.CompactTextString(m) }
func (*RouterInfo) ProtoMessage()    {}
func (*RouterInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{0}
}

func (m *RouterInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouterInfo.Unmarshal(m, b)
}
func (m *RouterInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouterInfo.Marshal(b, m, deterministic)
}
func (m *RouterInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouterInfo.Merge(m, src)
}
func (m *RouterInfo) XXX_Size() int {
	return xxx_messageInfo_RouterInfo.Size(m)
}
func (m *RouterInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RouterInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RouterInfo proto.InternalMessageInfo

func (m *RouterInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type RouterId struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouterId) Reset()         { *m = RouterId{} }
func (m *RouterId) String() string { return proto.CompactTextString(m) }
func (*RouterId) ProtoMessage()    {}
func (*RouterId) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{1}
}

func (m *RouterId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouterId.Unmarshal(m, b)
}
func (m *RouterId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouterId.Marshal(b, m, deterministic)
}
func (m *RouterId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouterId.Merge(m, src)
}
func (m *RouterId) XXX_Size() int {
	return xxx_messageInfo_RouterId.Size(m)
}
func (m *RouterId) XXX_DiscardUnknown() {
	xxx_messageInfo_RouterId.DiscardUnknown(m)
}

var xxx_messageInfo_RouterId proto.InternalMessageInfo

func (m *RouterId) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type FindAll struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindAll) Reset()         { *m = FindAll{} }
func (m *FindAll) String() string { return proto.CompactTextString(m) }
func (*FindAll) ProtoMessage()    {}
func (*FindAll) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{2}
}

func (m *FindAll) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAll.Unmarshal(m, b)
}
func (m *FindAll) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAll.Marshal(b, m, deterministic)
}
func (m *FindAll) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAll.Merge(m, src)
}
func (m *FindAll) XXX_Size() int {
	return xxx_messageInfo_FindAll.Size(m)
}
func (m *FindAll) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAll.DiscardUnknown(m)
}

var xxx_messageInfo_FindAll proto.InternalMessageInfo

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type AllRouter struct {
	RouterInfo           []*RouterInfo `protobuf:"bytes,1,rep,name=router_info,json=routerInfo,proto3" json:"router_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AllRouter) Reset()         { *m = AllRouter{} }
func (m *AllRouter) String() string { return proto.CompactTextString(m) }
func (*AllRouter) ProtoMessage()    {}
func (*AllRouter) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{4}
}

func (m *AllRouter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllRouter.Unmarshal(m, b)
}
func (m *AllRouter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllRouter.Marshal(b, m, deterministic)
}
func (m *AllRouter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllRouter.Merge(m, src)
}
func (m *AllRouter) XXX_Size() int {
	return xxx_messageInfo_AllRouter.Size(m)
}
func (m *AllRouter) XXX_DiscardUnknown() {
	xxx_messageInfo_AllRouter.DiscardUnknown(m)
}

var xxx_messageInfo_AllRouter proto.InternalMessageInfo

func (m *AllRouter) GetRouterInfo() []*RouterInfo {
	if m != nil {
		return m.RouterInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*RouterInfo)(nil), "router.RouterInfo")
	proto.RegisterType((*RouterId)(nil), "router.RouterId")
	proto.RegisterType((*FindAll)(nil), "router.FindAll")
	proto.RegisterType((*Response)(nil), "router.Response")
	proto.RegisterType((*AllRouter)(nil), "router.AllRouter")
}

func init() {
	proto.RegisterFile("router.proto", fileDescriptor_367072455c71aedc)
}

var fileDescriptor_367072455c71aedc = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0xca, 0x2f, 0x2d,
	0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x64, 0xb8, 0xb8,
	0x82, 0xc0, 0x2c, 0xcf, 0xbc, 0xb4, 0x7c, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0xe6, 0x20, 0xa6, 0xcc, 0x14, 0x25, 0x29, 0x2e, 0x0e, 0xa8, 0x6c, 0x0a, 0x86, 0x1c,
	0x27, 0x17, 0xbb, 0x5b, 0x66, 0x5e, 0x8a, 0x63, 0x4e, 0x8e, 0x92, 0x0c, 0x17, 0x47, 0x50, 0x6a,
	0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x00, 0x17, 0x73, 0x6e, 0x71, 0x3a, 0x58, 0x1d, 0x67,
	0x10, 0x88, 0xa9, 0xe4, 0xc0, 0xc5, 0xe9, 0x98, 0x93, 0x03, 0x31, 0x47, 0xc8, 0x98, 0x8b, 0x1b,
	0x62, 0x73, 0x7c, 0x66, 0x5e, 0x5a, 0xbe, 0x04, 0xa3, 0x02, 0xb3, 0x06, 0xb7, 0x91, 0x90, 0x1e,
	0xd4, 0x6d, 0x08, 0xa7, 0x04, 0x71, 0x15, 0xc1, 0xd9, 0x46, 0x73, 0x98, 0xb8, 0xd8, 0xe0, 0xfa,
	0x39, 0x1d, 0x53, 0x52, 0xa0, 0x1c, 0x2c, 0xfa, 0xa4, 0x04, 0xe0, 0x62, 0x50, 0x17, 0x29, 0x31,
	0x08, 0x99, 0x70, 0xf1, 0xb8, 0xa4, 0xe6, 0xa4, 0x96, 0xa4, 0x42, 0xf5, 0x09, 0xa0, 0xe9, 0x4b,
	0xc1, 0xaa, 0xcb, 0x8c, 0x8b, 0x27, 0xb4, 0x20, 0x25, 0x11, 0xae, 0x8b, 0x58, 0xdb, 0x2c, 0xb8,
	0xf8, 0x40, 0x01, 0x03, 0x51, 0xe5, 0x54, 0xe9, 0xe9, 0x82, 0xc5, 0x3e, 0x2c, 0x66, 0x29, 0x31,
	0x08, 0x99, 0x72, 0xf1, 0x42, 0x83, 0x14, 0x6a, 0x25, 0x3f, 0x4c, 0x19, 0x54, 0x58, 0x4a, 0x10,
	0x26, 0x00, 0x57, 0xa3, 0xc4, 0xe0, 0x24, 0x1e, 0x25, 0xaa, 0xa7, 0x0f, 0x8e, 0x56, 0x7d, 0x88,
	0xac, 0x35, 0x84, 0x4a, 0x62, 0x03, 0x0b, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x45, 0x1f,
	0xb9, 0xf6, 0xfb, 0x01, 0x00, 0x00,
}
