// Code generated by protoc-gen-go. DO NOT EDIT.
// source: router.proto

package router

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RouterInfo struct {
	Id                   int64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RouterName           string        `protobuf:"bytes,2,opt,name=router_name,json=routerName,proto3" json:"router_name,omitempty"`
	RouterNamespace      string        `protobuf:"bytes,3,opt,name=router_namespace,json=routerNamespace,proto3" json:"router_namespace,omitempty"`
	RouterHost           string        `protobuf:"bytes,4,opt,name=router_host,json=routerHost,proto3" json:"router_host,omitempty"`
	RouterPath           []*RouterPath `protobuf:"bytes,5,rep,name=router_path,json=routerPath,proto3" json:"router_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RouterInfo) Reset()         { *m = RouterInfo{} }
func (m *RouterInfo) String() string { return proto.CompactTextString(m) }
func (*RouterInfo) ProtoMessage()    {}
func (*RouterInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{0}
}

func (m *RouterInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouterInfo.Unmarshal(m, b)
}
func (m *RouterInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouterInfo.Marshal(b, m, deterministic)
}
func (m *RouterInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouterInfo.Merge(m, src)
}
func (m *RouterInfo) XXX_Size() int {
	return xxx_messageInfo_RouterInfo.Size(m)
}
func (m *RouterInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RouterInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RouterInfo proto.InternalMessageInfo

func (m *RouterInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RouterInfo) GetRouterName() string {
	if m != nil {
		return m.RouterName
	}
	return ""
}

func (m *RouterInfo) GetRouterNamespace() string {
	if m != nil {
		return m.RouterNamespace
	}
	return ""
}

func (m *RouterInfo) GetRouterHost() string {
	if m != nil {
		return m.RouterHost
	}
	return ""
}

func (m *RouterInfo) GetRouterPath() []*RouterPath {
	if m != nil {
		return m.RouterPath
	}
	return nil
}

type RouterPath struct {
	Id                       int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RouterId                 int64    `protobuf:"varint,2,opt,name=router_id,json=routerId,proto3" json:"router_id,omitempty"`
	RouterPathName           string   `protobuf:"bytes,3,opt,name=router_path_name,json=routerPathName,proto3" json:"router_path_name,omitempty"`
	RouterBackendService     string   `protobuf:"bytes,4,opt,name=router_backend_service,json=routerBackendService,proto3" json:"router_backend_service,omitempty"`
	RouterBackendServicePort int32    `protobuf:"varint,5,opt,name=router_backend_service_port,json=routerBackendServicePort,proto3" json:"router_backend_service_port,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *RouterPath) Reset()         { *m = RouterPath{} }
func (m *RouterPath) String() string { return proto.CompactTextString(m) }
func (*RouterPath) ProtoMessage()    {}
func (*RouterPath) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{1}
}

func (m *RouterPath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouterPath.Unmarshal(m, b)
}
func (m *RouterPath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouterPath.Marshal(b, m, deterministic)
}
func (m *RouterPath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouterPath.Merge(m, src)
}
func (m *RouterPath) XXX_Size() int {
	return xxx_messageInfo_RouterPath.Size(m)
}
func (m *RouterPath) XXX_DiscardUnknown() {
	xxx_messageInfo_RouterPath.DiscardUnknown(m)
}

var xxx_messageInfo_RouterPath proto.InternalMessageInfo

func (m *RouterPath) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RouterPath) GetRouterId() int64 {
	if m != nil {
		return m.RouterId
	}
	return 0
}

func (m *RouterPath) GetRouterPathName() string {
	if m != nil {
		return m.RouterPathName
	}
	return ""
}

func (m *RouterPath) GetRouterBackendService() string {
	if m != nil {
		return m.RouterBackendService
	}
	return ""
}

func (m *RouterPath) GetRouterBackendServicePort() int32 {
	if m != nil {
		return m.RouterBackendServicePort
	}
	return 0
}

type RouterId struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouterId) Reset()         { *m = RouterId{} }
func (m *RouterId) String() string { return proto.CompactTextString(m) }
func (*RouterId) ProtoMessage()    {}
func (*RouterId) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{2}
}

func (m *RouterId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouterId.Unmarshal(m, b)
}
func (m *RouterId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouterId.Marshal(b, m, deterministic)
}
func (m *RouterId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouterId.Merge(m, src)
}
func (m *RouterId) XXX_Size() int {
	return xxx_messageInfo_RouterId.Size(m)
}
func (m *RouterId) XXX_DiscardUnknown() {
	xxx_messageInfo_RouterId.DiscardUnknown(m)
}

var xxx_messageInfo_RouterId proto.InternalMessageInfo

func (m *RouterId) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type FindAll struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindAll) Reset()         { *m = FindAll{} }
func (m *FindAll) String() string { return proto.CompactTextString(m) }
func (*FindAll) ProtoMessage()    {}
func (*FindAll) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{3}
}

func (m *FindAll) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAll.Unmarshal(m, b)
}
func (m *FindAll) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAll.Marshal(b, m, deterministic)
}
func (m *FindAll) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAll.Merge(m, src)
}
func (m *FindAll) XXX_Size() int {
	return xxx_messageInfo_FindAll.Size(m)
}
func (m *FindAll) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAll.DiscardUnknown(m)
}

var xxx_messageInfo_FindAll proto.InternalMessageInfo

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{4}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type AllRouter struct {
	RouterInfo           []*RouterInfo `protobuf:"bytes,1,rep,name=router_info,json=routerInfo,proto3" json:"router_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AllRouter) Reset()         { *m = AllRouter{} }
func (m *AllRouter) String() string { return proto.CompactTextString(m) }
func (*AllRouter) ProtoMessage()    {}
func (*AllRouter) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{5}
}

func (m *AllRouter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllRouter.Unmarshal(m, b)
}
func (m *AllRouter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllRouter.Marshal(b, m, deterministic)
}
func (m *AllRouter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllRouter.Merge(m, src)
}
func (m *AllRouter) XXX_Size() int {
	return xxx_messageInfo_AllRouter.Size(m)
}
func (m *AllRouter) XXX_DiscardUnknown() {
	xxx_messageInfo_AllRouter.DiscardUnknown(m)
}

var xxx_messageInfo_AllRouter proto.InternalMessageInfo

func (m *AllRouter) GetRouterInfo() []*RouterInfo {
	if m != nil {
		return m.RouterInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*RouterInfo)(nil), "router.RouterInfo")
	proto.RegisterType((*RouterPath)(nil), "router.RouterPath")
	proto.RegisterType((*RouterId)(nil), "router.RouterId")
	proto.RegisterType((*FindAll)(nil), "router.FindAll")
	proto.RegisterType((*Response)(nil), "router.Response")
	proto.RegisterType((*AllRouter)(nil), "router.AllRouter")
}

func init() {
	proto.RegisterFile("router.proto", fileDescriptor_367072455c71aedc)
}

var fileDescriptor_367072455c71aedc = []byte{
	// 421 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0xab, 0xda, 0x40,
	0x14, 0x35, 0x49, 0xb5, 0xe6, 0x6a, 0x35, 0x1d, 0xfa, 0x31, 0x68, 0xa1, 0x61, 0x56, 0xe9, 0x46,
	0x41, 0x6d, 0x29, 0x94, 0x42, 0x15, 0x29, 0x75, 0x53, 0x64, 0x4a, 0x37, 0xdd, 0x48, 0x74, 0xc6,
	0x1a, 0x1a, 0x33, 0x21, 0x99, 0x16, 0xfa, 0x5f, 0xde, 0x6f, 0x79, 0xbf, 0xe3, 0xfd, 0x9c, 0x47,
	0x66, 0x26, 0x31, 0xf8, 0xb2, 0x78, 0x2b, 0xef, 0x9c, 0x7b, 0xce, 0xbd, 0xe7, 0x5c, 0x0c, 0xf4,
	0x33, 0xf1, 0x57, 0xf2, 0x6c, 0x92, 0x66, 0x42, 0x0a, 0xd4, 0xd1, 0x2f, 0x72, 0x6b, 0x01, 0x50,
	0x55, 0x6e, 0x92, 0xa3, 0x40, 0x03, 0xb0, 0x23, 0x86, 0x2d, 0xdf, 0x0a, 0x1c, 0x6a, 0x47, 0x0c,
	0xbd, 0x85, 0x9e, 0x26, 0xee, 0x92, 0xf0, 0xcc, 0xb1, 0xed, 0x5b, 0x81, 0x4b, 0x41, 0x43, 0xdf,
	0xc3, 0x33, 0x47, 0xef, 0xc0, 0xab, 0x11, 0xf2, 0x34, 0x3c, 0x70, 0xec, 0x28, 0xd6, 0xf0, 0xc2,
	0x52, 0x70, 0x6d, 0xd6, 0x49, 0xe4, 0x12, 0x3f, 0xa9, 0xcf, 0xfa, 0x26, 0x72, 0x89, 0xe6, 0x15,
	0x21, 0x0d, 0xe5, 0x09, 0xb7, 0x7d, 0x27, 0xe8, 0xcd, 0xd0, 0xc4, 0xf8, 0xd6, 0x2e, 0xb7, 0xa1,
	0x3c, 0x95, 0xa2, 0xa2, 0x26, 0x77, 0x55, 0x80, 0xe2, 0xf9, 0x20, 0xc0, 0x18, 0x5c, 0x33, 0x33,
	0x62, 0xca, 0xbe, 0x43, 0xbb, 0x1a, 0xd8, 0x30, 0x14, 0x54, 0xe6, 0x8b, 0x85, 0x3a, 0xa2, 0x36,
	0x3f, 0xb8, 0x6c, 0x50, 0x31, 0x17, 0xf0, 0xca, 0x30, 0xf7, 0xe1, 0xe1, 0x0f, 0x4f, 0xd8, 0x2e,
	0xe7, 0xd9, 0xbf, 0xe8, 0xc0, 0x4d, 0x8c, 0x17, 0xba, 0xbb, 0xd2, 0xcd, 0x1f, 0xba, 0x87, 0x3e,
	0xc3, 0xb8, 0x59, 0xb5, 0x4b, 0x45, 0x26, 0x71, 0xdb, 0xb7, 0x82, 0x36, 0xc5, 0x4d, 0xd2, 0xad,
	0xc8, 0x24, 0x19, 0x41, 0x97, 0x96, 0x56, 0xaf, 0x72, 0x11, 0x17, 0x9e, 0x7e, 0x8d, 0x12, 0xb6,
	0x8c, 0x63, 0xf2, 0x06, 0xba, 0x94, 0xe7, 0xa9, 0x48, 0x72, 0x8e, 0x3c, 0x70, 0xce, 0xf9, 0x6f,
	0xc5, 0x73, 0x69, 0x51, 0x92, 0x2f, 0xe0, 0x2e, 0xe3, 0x58, 0xcf, 0xa9, 0x5d, 0x38, 0x4a, 0x8e,
	0x02, 0x5b, 0x4d, 0x17, 0x2e, 0xfe, 0x07, 0xe5, 0x85, 0x8b, 0x7a, 0x76, 0x63, 0x43, 0xa7, 0xd2,
	0xbb, 0x4b, 0xc6, 0xcc, 0xa3, 0x41, 0x37, 0xf2, 0x2a, 0xcc, 0x38, 0x22, 0x2d, 0xb4, 0x80, 0xfe,
	0x9a, 0xc7, 0x5c, 0x72, 0xa3, 0xf3, 0xae, 0x74, 0xac, 0x51, 0xf5, 0x01, 0xfa, 0x3f, 0x53, 0x16,
	0x56, 0xaa, 0xc7, 0x6e, 0xfb, 0x08, 0x83, 0xe2, 0x30, 0x9a, 0xb5, 0xfa, 0xbf, 0x59, 0x37, 0xec,
	0x6b, 0x98, 0x45, 0x5a, 0xe8, 0x3d, 0x3c, 0x33, 0x27, 0x35, 0x2b, 0x87, 0x25, 0xcd, 0xc0, 0xa3,
	0xe7, 0x25, 0x50, 0x71, 0x48, 0x6b, 0xf5, 0xfa, 0xd7, 0xcb, 0xc9, 0x54, 0x7d, 0x54, 0x53, 0xdd,
	0xfd, 0xa4, 0x7f, 0xf6, 0x1d, 0x05, 0xce, 0xef, 0x03, 0x00, 0x00, 0xff, 0xff, 0x96, 0xfc, 0x0c,
	0xcf, 0x79, 0x03, 0x00, 0x00,
}
